apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-noticia-deployment
spec:
  selector:
    matchLabels:
      app: aplicacao-noticia-pod
  template:
    metadata:
      labels:
        app: aplicacao-noticia-pod
    spec:
      containers:
      - name: aplicacao-noticia-deployment
        image: jnlucas/image-phpmysql:latest
        ports:
        - containerPort: 80
